#ifndef __XIOS_NODE_TYPE__
#define __XIOS_NODE_TYPE__

#include "axis.hpp"
#include "domain.hpp"
#include "field.hpp"
#include "file.hpp"
#include "grid.hpp"
#include "variable.hpp"
#include "context.hpp"
#include "transformation.hpp"
#include "inverse_axis.hpp"
#include "zoom_axis.hpp"
#include "interpolate_axis.hpp"
#include "extract_axis.hpp"
#include "zoom_domain.hpp"
#include "interpolate_domain.hpp"
#include "generate_rectilinear_domain.hpp"
#include "scalar.hpp"
#include "reduce_axis_to_scalar.hpp"
#include "reduce_domain_to_axis.hpp"
#include "reduce_axis_to_axis.hpp"
#include "extract_domain_to_axis.hpp"
#include "compute_connectivity_domain.hpp"
#include "expand_domain.hpp"
#include "extract_axis_to_scalar.hpp"
#include "reduce_domain_to_scalar.hpp"
#include "temporal_splitting.hpp"
#include "duplicate_scalar_to_axis.hpp"
#include "reduce_scalar_to_scalar.hpp"
#include "reorder_domain.hpp"
#include "extract_domain.hpp"


#endif // __XIOS_NODE_TYPE__
